/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appHasAGoodbye() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGoodBye(), "app should have a greeting");
        assertEquals("Bye World!", classUnderTest.getGoodBye());
    }

    @Test void hashTableHasTable() {
        HashTable classUnderTest = new HashTable();
        assertEquals(0, classUnderTest.size());
    }

    @Test void hashTable() {
        HashTable classUnderTest = new HashTable();
        assertEquals(0, classUnderTest.size());
    }

    
}
