/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void hashTableHasTable() {
        HashTable classUnderTest = new HashTable();
        assertEquals(0, classUnderTest.size());
    }

    @Test void hashTable() {
        HashTable classUnderTest = new HashTable();
        assertEquals(0, classUnderTest.size());
    }

    // @Test void textParseTest() {
    //     TextParsing classUnderTest = new TextParsing();
    //     assertNotEquals(void.class, classUnderTest.parseFile("..\\resources\\groceries.txt"));
    // }


}
