/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.FileNotFoundException;

class AppTest {
    @Test void hashTableIsEmpty() {
        HashTable classUnderTest = new HashTable();
        assertEquals(0, classUnderTest.size());
    }

    @Test void hashTableHasElements() {
        HashTable classUnderTest = new HashTable();
        classUnderTest.insert("alpha");
        classUnderTest.insert("beta");
        classUnderTest.insert("gamma");
        assertEquals(3, classUnderTest.size());
    }

    @Test void textParseTest() throws FileNotFoundException {
        TextParsing classUnderTest = new TextParsing();
        assertEquals(14, classUnderTest.parseFile(".\\src\\main\\resources\\groceries.txt"));
    }

    @Test void textAnagramTest() throws FileNotFoundException {
        TextParsing classUnderTest = new TextParsing();
        assertEquals(13, classUnderTest.parseAnagram(".\\src\\main\\resources\\groceries.txt"));
    }


}
