/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;

public class TextParsing {
    public int parseFile(String filePath) throws FileNotFoundException {
        HashTable table = new HashTable();
        
        File file = new File(filePath); 
        Scanner sc = new Scanner(file);

        sc.useDelimiter("[^a-zA-Z]+");
        while(sc.hasNext()){
            table.insert(sc.next());
        }

        sc.close();
        return(table.size());
    }

    public int parseAnagram(String filePath) throws FileNotFoundException {
        HashTable table = new HashTable();
        
        File file = new File(filePath); 
        Scanner sc = new Scanner(file);

        sc.useDelimiter("[^a-zA-Z]+");
        while(sc.hasNext()){

            String anagram = sc.next().toLowerCase();
            char[] temp = anagram.toCharArray();
            Arrays.sort(temp);
            anagram = new String(temp);

            if(!table.contains(anagram)){
                table.insert(anagram);
            }
        }

        sc.close();
        table.printItems();

        return table.size();
    }

    public static void main(String[] args) throws FileNotFoundException {
        TextParsing classUnderTest = new TextParsing();
        classUnderTest.parseAnagram("app\\src\\main\\resources\\groceries.txt");
    }
    
}
